site_name: ViPLab
#plugins:
#    - search
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
theme:
  name: null
  custom_dir: 'cinder'
nav:
  - Home: index.md
  - Integration: integration/index.md
  - User Guide: viplab-frontend/index.md
  - Developer Guide: viplab3.0/index.md
extra:
  collapse_toc: false
